<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 1 </p>

In [2]:
# importing numpy
import numpy as np

In [6]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
array_1 = np.array([1,2,3,5,0])
print(array_1)

[1 2 3 5 0]


In [8]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
array_2 = np.array([3, -1, 3, 7, 2])
print(array_2)

[ 3 -1  3  7  2]


In [9]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
array_3 =  np.array([0, 0, 0, 0])
print(array_3)

[0 0 0 0]


In [10]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
array_4 = np.array([56, -2, 7])
array_size = array_4.nbytes
print(array_size)

24


In [11]:
# Create a numpy array with 10 zeros and print the array.
array_5 = np.zeros((10,), dtype=int)
# Create a numpy array with 6 ones and print the array.
array_6 = np.ones((1,), dtype=int)
# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
array_7 = np.full(12, 3)

In [14]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
array_8 = np.arange(8, 21, 1, dtype=int)
print(array_8)
# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
array_9 = np.arange(8, 21, 2, dtype=int)
print(array_9)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [7]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
array_10 
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?
