<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 8</p>

In [5]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [2]:
# Import the built-in iris dataset to work with
iris = datasets.load_iris() # the dataset consists of 3 different types of irises' (Setosa, Versicolour, and Virginica) petal and sepal length
print("iris dataset",iris.data[:10,:])
X = iris.data[:, :2] # We only want to use the first two features (Sepal Length, Sepal Width)
y = iris.target # corresponding to 'setosa', 'versicolor', 'virginica
print("iris target",y[:10,])

iris dataset [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
iris target [0 0 0 0 0 0 0 0 0 0]


In [3]:
# Develop a linear Support Vector Machine to classify the irises
# Use GridSearchCV to optimize the model's hyperparameters (C, gamma, kernel)
# Compare the accuracies of the above two models

In [9]:
# Develop a linear Support Vector Machine to classify the irises
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 1. Train a linear SVM model
linear_svm = SVC(kernel='linear')
linear_svm.fit(X_train, y_train)

# Make predictions using the linear SVM
y_pred_linear = linear_svm.predict(X_test)

# Evaluate the linear SVM accuracy
linear_accuracy = accuracy_score(y_test, y_pred_linear)
print(f"Linear SVM Accuracy: {linear_accuracy:.2f}")

Linear SVM Accuracy: 0.90


In [7]:
# Use GridSearchCV to optimize the model's hyperparameters (C, gamma, kernel)
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [1, 0.1, 0.01, 0.001],
    'kernel': ['linear', 'rbf']
}

grid_search = GridSearchCV(SVC(), param_grid, refit=True, verbose=2)
grid_search.fit(X_train, y_train)

# Display the best parameters and score
print("Best Parameters from GridSearchCV:", grid_search.best_params_)

# Make predictions using the best model from GridSearchCV
y_pred_best = grid_search.best_estimator_.predict(X_test)

# Evaluate the optimized SVM accuracy
optimized_accuracy = accuracy_score(y_test, y_pred_best)
print(f"Optimized SVM Accuracy: {optimized_accuracy:.2f}")

Fitting 5 folds for each of 32 candidates, totalling 160 fits
[CV] END ......................C=0.1, gamma=1, kernel=linear; total time=   0.0s
[CV] END ......................C=0.1, gamma=1, kernel=linear; total time=   0.0s
[CV] END ......................C=0.1, gamma=1, kernel=linear; total time=   0.0s
[CV] END ......................C=0.1, gamma=1, kernel=linear; total time=   0.0s
[CV] END ......................C=0.1, gamma=1, kernel=linear; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END ....................C=0.1, gamma=0.1, kernel=linear; total time=   0.0s
[CV] END ....................C=0.1, gamma=0.1, 

In [8]:
# Compare the accuracies of the above two models
print(f"Comparison of accuracies:")
print(f"Linear SVM Accuracy: {linear_accuracy:.2f}")
print(f"Optimized SVM Accuracy (from GridSearchCV): {optimized_accuracy:.2f}")

Comparison of accuracies:
Linear SVM Accuracy: 0.90
Optimized SVM Accuracy (from GridSearchCV): 0.90
