<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

In [2]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

In [6]:
matrix_a = np.array([[5,2, 3], [6, 1, 3],[2, 4, 1]])

In [7]:
matrix_a

array([[5, 2, 3],
       [6, 1, 3],
       [2, 4, 1]])

In [4]:
matrix_b = np.array([[5,2],[6,1]])
print(matrix_b)

[[5 2]
 [6 1]]


In [5]:
matrix_c= np.array([[1,3],[4,1]])
print (matrix_c)

[[1 3]
 [4 1]]


In [9]:
matrix_d = np.array([[4, -7, 4], [5, 6, -1],[-4, 2, 5]])
print(matrix_d)

[[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]


In [11]:
matrix_ad = np.matmul(matrix_a,matrix_d).shape
matrix_ad

(3, 3)

In [13]:
matrix_da = np.matmul(matrix_d,matrix_a).shape
matrix_da

(3, 3)

In [ ]:
##AD and DA are equal

In [17]:
# Get the number of rows and columns
num_rows = matrix_b.shape[0]
num_cols = matrix_b.shape[1]

# Initialize the result matrix with zeros
result_matrix = np.zeros((num_rows, num_cols), dtype=int)

# Compute the dot product manually
for i in range(num_rows):
    for j in range(num_cols):
        sum_product = 0
        for k in range(num_cols):
            sum_product += matrix_b[i, k] * matrix_b[k, j]
        result_matrix[i, j] = sum_product

# Print the result matrix
print("\nDot product of Matrix B with itself:")
print(result_matrix)


Dot product of Matrix B with itself:
[[37 12]
 [36 13]]


In [16]:
# Define the matrix
# Calculate the determinant
determinant = (matrix_b[0, 0] * matrix_b[1, 1]) - (matrix_b[0, 1] * matrix_b[1, 0])

# Calculate the matrix of cofactors
cofactor_matrix = np.array([[matrix_b[1, 1], -matrix_b[0, 1]],
                            [-matrix_b[1, 0], matrix_b[0, 0]]])

# Calculate the inverse by dividing the cofactor matrix by the determinant
inverse_matrix = cofactor_matrix / determinant

# Print the results
print("\nInverse of Matrix B:")
print(inverse_matrix)



Inverse of Matrix B:
[[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]


In [19]:
inverse_matrix_b = np.linalg.inv(matrix_b)
inverse_matrix_b

array([[-0.14285714,  0.28571429],
       [ 0.85714286, -0.71428571]])

In [20]:
dot_matrix_b = np.dot(matrix_b, matrix_b)
dot_matrix_b

array([[37, 12],
       [36, 13]])

In [22]:
inverse_matrix_d = np.linalg.inv(matrix_d)
inverse_matrix_d

array([[ 0.07785888,  0.10462287, -0.04136253],
       [-0.05109489,  0.08759124,  0.05839416],
       [ 0.08272506,  0.0486618 ,  0.14355231]])

In [24]:
d_d_minus_1 = np.matmul(matrix_d,inverse_matrix_d).shape
d_d_minus_1

(3, 3)

In [26]:
d_minus_1_d = np.matmul(inverse_matrix_d,matrix_d).shape
d_d_minus_1

(3, 3)